### PR TITLE
fix/scroll conflict between column and map in MapPickerBox

### LINKED ISSUE #80: Fix the vertical scrolling problem on the LessonEditor and MapPickerBox
When one try to scroll vertically on the map screen it actually scroll through the whole screen

### PR DESCRIPTION
**Pull request by MPepito**
## Description:

This PR fix #80 a scrolling conflict between the outer Column and the GoogleMap component within the MapPickerBox. Previously, scrolling on the map was inadvertently intercepted by the Column, causing the entire screen to scroll instead of allowing interaction directly with the map. This fix ensures that touch gestures on the map are handled within the MapPickerBox, allowing users to scroll and zoom on the map without affecting the Column's scrolling.

Further details on the screen can be found on #79 

## Changes Made:

Added pointerInput to the GoogleMap modifier within MapPickerBox to handle gestures specifically on the map component.
Used detectTransformGestures to intercept panning and zooming gestures on the map, preventing these gestures from propagating to the Column.
Reversed panning direction within MapPickerBox to provide a natural map interaction experience.

## Design suggestions

We could use a Dialogue instead of a Box to easily transfer these interactions between components

### CODE REVIEW

File: app/src/main/java/com/github/se/project/ui/map/LocationPickerScreen.kt [hunk 1]
```diff
@@ -34,9 +37,26 @@ fun MapPickerBox(
...
 
-  Column(modifier = Modifier.fillMaxWidth().padding(16.dp)) {
+  Column (modifier = Modifier.fillMaxWidth().padding(16.dp)) {
     GoogleMap(
-        modifier = Modifier.fillMaxWidth().height(400.dp),
+        modifier = Modifier
+            .fillMaxWidth()
+            .height(400.dp)
+            //Pass the scrolling and zooming gestures to the map
+            .pointerInput(Unit) {
```
Comment (alexs-rufer) [inline app/src/main/java/com/github/se/project/ui/map/LocationPickerScreen.kt]: This indeed is a solution to solve the scrolling problem, nice job!

**Review by alexs-rufer — APPROVED** [review]
good job :)

**Review by alexs-rufer — APPROVED** [review]
already approved.
